### ISSUE TITLE
user-defined function

### ISSUE THREAD

**Issue by AliCharkhi** [medianasoft/MedianaDesigner#1]
Thanks for this helpful package. It is a great complementary for Mediana Package.
I was wondering if it supports user-defined functions as well. 
Thanks in advance for your response!

Ali

**Comment by alexdmitrienko** [comment]
Hi Ali, thank you for your interest in this project. Unlike the original Mediana package, which was written in R (and is rather slow as a result), the simulation engine in this new package has been written in C++. It's much faster but the price we have to pay for it is that it's much more difficult to support user-defined functions, essentially these functions will need to be written in C++ as well. We will try to find a reasonable compromise.
