### ISSUE TITLE
test word document size

### ISSUE THREAD

**Issue by davidgohel** [medianasoft/MedianaDesigner#2]
Hello 

I am the maintainer of package 'officer'. I am preparing a new version for CRAN. There is an issue with reverse dependency 'MedianaDesigner'.  

This [test](https://github.com/medianasoft/MedianaDesigner/blob/master/tests/testthat/test-ADRand.r#L123) `expect_true(file.size(temp_file) > 35000)` is broken with the new version of officer. The new version is creating lighter docx files, this is a (surprising) side effect of the refactoring of sections. However, the document is correct, the rendering is the same.

[new.docx](https://github.com/medianasoft/MedianaDesigner/files/10231620/new.docx)
[old.docx](https://github.com/medianasoft/MedianaDesigner/files/10231621/old.docx)

<img width="1670" alt="Capture d’écran 2022-12-14 à 21 53 34" src="https://user-images.githubusercontent.com/4331618/207712371-4650dd5c-4b06-4b04-9712-4c98f7dd7973.png">

Could you remove that test so that the CRAN submission is not impacted?

**Comment by vicdmitrienko** [comment]
David, thanks for your package! Glad to see an update from you with optimization effects. Of course, fixing the tests is not a problem. Please wait a few seconds.

**Comment by davidgohel** [comment]
thank you @vicdmitrienko for your quick answer

Let me know when you will have passed the CRAN submission, I will then submit officer :)

KR
David

**Comment by vicdmitrienko** [comment]
@davidgohel, updated version of MedianaDesigner package is successfully published on CRAN. Thank you :)

**Comment by davidgohel** [comment]
thank you!
